spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size=20
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  profiles:
    active: prod
